library(xgboost)
printf <- function(...) invisible(print(sprintf(...)))

print(date())
source("modelBuildingVars.R")
source("initLoans.R")
print(date())

master_df <- df
if(ONE_IN_N > 1)
{
  print(paste0("*************WARNING!!!!!! ONLY TAKING ONE IN ",ONE_IN_N," ITEMS!!!!!!!!!"))
  df$random_sample <- sample.int(ONE_IN_N, size=nrow(df), replace=TRUE)
  master_df <- df[which(df$random_sample==1),]
}


# Remember, can also set this before each do_one_xgb_crossval.r call.
# If you do, you'll want to do the override_auto_filename stuff.
model_params = c("MTHS_SINCE_LAST_MAJOR_DEROG","delinq_2yrs","latitude","longitude","jobtitlegood", "EMPLOYMENT_LENGTH",
                 "REVOLVING_UTILIZATION","INQUIRIES_IN_LAST_6_MONTHS", "after_loan_monthly_income","dti_frac",
                 "FICO_RANGE_LOW","purp_spec_badness","LOAN_AMOUNT", "is_rent")


print(paste0(nrow(master_df)," rows in master_df"))

#Build a uniformly shuffled even NUM_CROSSVAL_RUNS-way split for the CV runs
#===========================================================================
rawIndices <- rep.int(0,0)
totalUnassigned <- nrow(master_df)
for(i in seq(1, NUM_CROSSVAL_RUNS-1))
{
    curAssignSize <- round(totalUnassigned / (NUM_CROSSVAL_RUNS-(i-1)))
    totalUnassigned <- totalUnassigned - curAssignSize
    rawIndices <- c(rawIndices, rep.int(i, curAssignSize))
}
rawIndices <- c(rawIndices, rep.int(NUM_CROSSVAL_RUNS, totalUnassigned))
master_df$crossvalSplit <- sample(rawIndices)
#===========================================================================

# DUMMY, for validation. (Way fewer rows, to finish very quickly).
#print("Now doing code validation. Don't forget to check that the DUMMY files were written!")
#source("crossvalRFdummy.R")

if(ONE_IN_N > 1)
{
  print(paste0("*************WARNING!!!!!! ONLY TAKING ONE IN ",ONE_IN_N," ITEMS!!!!!!!!!"))
}



out_filename_prefix = "cleaned-bbZIP_XGBv1.1_MAY2020"
compare_scatter_output_pdf = "cleaned-bbZIP_vs_without_vs_sep2019.pdf"
# If you want to put some previously generated results into the comparison scatterplot, do it here.
#compare_filenames = c()
compare_filenames = c(
    "recordkeeping/XGBv1_SEP2019_pareto.csv",
    "recordkeeping/XGBv1_SEP2019_doublecheck_pareto.csv",
    "recordkeeping/XGBv1_SEP2019_triplecheck_pareto.csv",
    "recordkeeping/XGBv1_MAY2020_pareto.csv")

# If T, you must set rfOutputFilename before each do_one_xgb_crossval. If F, it is autogenerated
# from the xgboost learning rate params.
override_auto_filename = T


# And now, the various model params to train. Remember, compare_filenames+these must be max 6,
# or compare_scatterplots.r will crash!
# ======================================================================




rfOutputFilename = "xgb_v1.1_cleaned-bBZIP"
model_type = "trad_is_bad"
model_params = c("MTHS_SINCE_LAST_MAJOR_DEROG","delinq_2yrs","badness_by_zip","jobtitlegood", "EMPLOYMENT_LENGTH",
                 "REVOLVING_UTILIZATION","INQUIRIES_IN_LAST_6_MONTHS", "after_loan_monthly_income","dti_frac",
                 "FICO_RANGE_LOW", "purp_spec_badness","LOAN_AMOUNT", "is_rent")
maxdepth = 11
numrounds = 200
eta = 0.1
minchildweight = 10
source("do_one_xgb_crossval.r")





# rfOutputFilename = "regr_badnessByZip_d11_r200_e0.1_mcw10"
# model_type = "writeoff_regression"
# model_params = c("MTHS_SINCE_LAST_MAJOR_DEROG","delinq_2yrs","badness_by_zip","jobtitlegood", "EMPLOYMENT_LENGTH",
#                  "REVOLVING_UTILIZATION","INQUIRIES_IN_LAST_6_MONTHS", "after_loan_monthly_income","dti_frac",
#                  "FICO_RANGE_LOW", "purp_spec_badness","LOAN_AMOUNT", "is_rent")
# maxdepth = 11
# numrounds = 200
# eta = 0.1
# minchildweight = 10
# source("do_one_xgb_crossval.r")




# rfOutputFilename = "trad_flood_same_tuning"
# model_type = "trad_is_bad"
# model_params = c("MTHS_SINCE_LAST_MAJOR_DEROG","delinq_2yrs","badness_by_zip","jobtitlegood", "EMPLOYMENT_LENGTH",
                 # "REVOLVING_UTILIZATION","INQUIRIES_IN_LAST_6_MONTHS", "after_loan_monthly_income","dti_frac",
                 # "FICO_RANGE_LOW", "purp_spec_badness","LOAN_AMOUNT", "is_rent", "floodclaims_per_person")
# maxdepth = 11
# numrounds = 200
# eta = 0.1
# minchildweight = 10
# source("do_one_xgb_crossval.r")





# rfOutputFilename = "regr_flood_same_tuning"
# model_type = "writeoff_regression"
# model_params = c("MTHS_SINCE_LAST_MAJOR_DEROG","delinq_2yrs","badness_by_zip","jobtitlegood", "EMPLOYMENT_LENGTH",
#                  "REVOLVING_UTILIZATION","INQUIRIES_IN_LAST_6_MONTHS", "after_loan_monthly_income","dti_frac",
#                  "FICO_RANGE_LOW", "purp_spec_badness","LOAN_AMOUNT", "is_rent", "floodclaims_per_person")
# maxdepth = 11
# numrounds = 200
# eta = 0.1
# minchildweight = 10
# source("do_one_xgb_crossval.r")


# ======================================================================


source("compare_scatterplots.r")
compareScatterplots(compare_filenames, compare_scatter_output_pdf)
print(paste("wrote scatterplot to", compare_scatter_output_pdf))


if(ONE_IN_N > 1)
{
  print(paste0("*************REMEMBER: ONLY TOOK ONE IN ",ONE_IN_N," ITEMS!!!!!!!!!"))
  print(paste0("*************REMEMBER: ONLY TOOK ONE IN ",ONE_IN_N," ITEMS!!!!!!!!!"))
  print(paste0("*************REMEMBER: ONLY TOOK ONE IN ",ONE_IN_N," ITEMS!!!!!!!!!"))
  print(paste0("*************REMEMBER: ONLY TOOK ONE IN ",ONE_IN_N," ITEMS!!!!!!!!!"))
  print(paste0("*************REMEMBER: ONLY TOOK ONE IN ",ONE_IN_N," ITEMS!!!!!!!!!"))
}

print("    DONE!  :)")
